# Generated by Django 3.2.9 on 2021-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanned',
            name='num',
            field=models.IntegerField(),
        ),
    ]
